# Generated by Django 5.0 on 2024-04-14 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('W', 'Watched'), ('UnW', 'Unwatched')], default='UnW', max_length=3)),
                ('media', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
