# Generated by Django 5.0 on 2024-04-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_lectures_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='category',
            field=models.CharField(choices=[('Ca', 'Calculus'), ('Ag', 'Algebra'), ('Sg', 'Solid Geometry'), ('Dy', 'Dynamics')], default='Ca', max_length=5),
        ),
    ]
