# Generated by Django 5.0 on 2024-04-17 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_lectures_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectures',
            old_name='user',
            new_name='author',
        ),
    ]
