# Generated by Django 5.0 on 2024-04-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0006_alter_lectures_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectures',
            name='media',
        ),
    ]
