# Generated by Django 5.0 on 2024-04-19 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0007_remove_lectures_media'),
    ]

    operations = [
    ]
