# Generated by Django 5.0 on 2024-04-19 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0008_auto_20240420_0005'),
    ]

    operations = [
    ]
