# Generated by Django 5.0 on 2024-04-19 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0010_auto_20240420_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectures',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lectures',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
