# Generated by Django 5.0 on 2024-05-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0012_lectures_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Job', models.CharField(max_length=200)),
                ('photo', models.FileField(blank=True, null=True, upload_to='static/images/')),
            ],
        ),
    ]
